### ISSUE TITLE
bimpm is too slow

### ISSUE THREAD

**Issue by codemayq** [nelson-liu/paraphrase-id-tensorflow#68]
thanks for your great work. 
but when I run bimpm.py with 1080 ti, the train speed is very low.I want to know whether it is common situation? I know this model is compalicated

**Comment by nelson-liu** [comment]
I agree that it's a bit slow, I also had this problem with the same GPU. If you manage to make it faster, I'd be happy to merge PRs 😄 .

Closing for now, reopen if you have further questions.
