### ISSUE TITLE
Can you share the evaluation results of your implementations?

### ISSUE THREAD

**Issue by rulai-huajunzeng** [nelson-liu/paraphrase-id-tensorflow#72]
Hi, Nelson, Thanks for sharing the code! If they are available, could you also share the accuracy of the implemented models on the Quora paraphrase data?

**Comment by nelson-liu** [comment]
Unfortunately, I can't find the final metrics anymore --- sorry! 😞 

if anyone has evaluated the model on the dataset, please chime in.
